# Generated by Django 5.1.2 on 2024-10-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Product',
            new_name='products',
        ),
    ]
